CREATE TABLE IF NOT EXISTS TEACHER (
    ID 	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME 	TEXT NOT NULL,
    USERNAME TEXT NOT NULL UNIQUE,
    PASSWORD 	TEXT NOT NULL,
    EMAIL 	TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS STUDENT (
    ID 	INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME 	TEXT NOT NULL,
    USERNAME TEXT NOT NULL UNIQUE,
    PASSWORD 	TEXT NOT NULL,
    EMAIL 	TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS CLASS (
    ID 	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME 	TEXT NOT NULL,
    SUBJECT TEXT NOT NULL,
    TID 	INTEGER NOT NULL,
    FOREIGN KEY (TID) REFERENCES TEACHER(ID)
);
CREATE TABLE IF NOT EXISTS CLASS_STUDENT (
    CID	INTEGER NOT NULL,
    SID 	INTEGER NOT NULL,
    FOREIGN KEY (SID) REFERENCES STUDENT(ID)
    FOREIGN KEY (CID) REFERENCES CLASS(ID)
);
CREATE TABLE IF NOT EXISTS ASSIGNMENT (
    ID 	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME 	TEXT NOT NULL,
    SID 	INTEGER NOT NULL,
    TID 	INTEGER NOT NULL,
    LINK 	TEXT NOT NULL,
    FOREIGN KEY (SID) REFERENCES STUDENT(ID)
    FOREIGN KEY (TID) REFERENCES TEACHER(ID)
);
CREATE TABLE IF NOT EXISTS ASSIGNMENT_STUDENT (
    AID 	INTEGER  NOT NULL ,
    LINK_RES 	TEXT ,
    SID 	INTEGER NOT NULL,
    FOREIGN KEY (SID) REFERENCES STUDENT(ID)
    FOREIGN KEY (AID) REFERENCES ASSIGNMENT(ID)
);
CREATE TABLE IF NOT EXISTS TEST (
    ID 	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME 	TEXT NOT NULL,
    SID 	INTEGER NOT NULL,
    TID 	INTEGER NOT NULL,
    LINK 	TEXT NOT NULL,
    TEST_DATE 	TEXT NOT NULL,
    FOREIGN KEY (SID) REFERENCES STUDENT(ID)
    FOREIGN KEY (TID) REFERENCES TEACHER(ID)
);
CREATE TABLE IF NOT EXISTS TEST_STUDENT (
    TID	INTEGER NOT NULL,
    SID 	INTEGER NOT NULL,
    LINK_RES 	TEXT,
    SCORE 	INTEGER,
    FOREIGN KEY (SID) REFERENCES STUDENT(ID)
    FOREIGN KEY (TID) REFERENCES TEST(ID)
);
CREATE TABLE IF NOT EXISTS LECTURE (
    ID 	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    LINK 	TEXT NOT NULL,
    SID 	INTEGER NOT NULL,
    TID 	INTEGER NOT NULL,
    FOREIGN KEY (SID) REFERENCES STUDENT(ID)
    FOREIGN KEY (TID) REFERENCES TEACHER(ID)
);